name: Add Pull Request Instructions
on:
  pull_request:
    types: [opened]
    branches:
      - 'gh-pages'
      - 'feature-homepage-launch'
      #1)The following branch will be removed after testing:
      - 'successtestbranch'

jobs:
  Add-Pull-Request-Instructions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create the message to post CAKE
      - name: Create Instruction
        uses: actions/github-script@v7
        id: instruction
        with:
          script: |
            const script = require('./github-actions/pr-instructions/create-instruction.js')
            return script({g: github, c: context}).then((instruction) => {
              return JSON.stringify({ instruction: instruction, issueNum: context.payload.number })
            })
      
      # Create an artifact with the message
      - name: Create Artifacts
        run: |
          mkdir -p addingPrInstructions/artifact
          echo ${{ steps.instruction.outputs.result }} > addingPrInstructions/artifact/artifact.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adding-pr-instructions-artifact
          path: addingPrInstructions/artifact/

  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          #2) For testing: Replace the token on line 48 with a user-generated PA token GAGA
          #3) For testing the success condition: For the github.request API calls, replace the 'owner' in lines 61 and 67 with your own github-handle for testing in local repo
          #4) For testing the fail condition: Follow step #3 and also change the username assignment from 'prAuthor' in line 56 to a random string
          github-token: ${{ secrets.HFLA_PB_TOKEN }}
          script: |
            const prAuthor = context.payload.sender.login;
            const prNumber = context.payload.number;
            try {
              const getMembershipStatus = await github.rest.teams.getMembershipForUserInOrg({
              org: 'hackforla',
              team_slug: 'website-write',
              username: 'YAGYAG'
              });
              console.log('Successfully verified!');
            } catch (verificationError) {
              if (verificationError.status==404) {
                await github.request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
                  owner : 'ajb176',
                  repo : 'website',
                  pull_number : prNumber,
                  state : 'closed'
                });
                await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/comments', {
                  owner : 'ajb176',
                  repo : 'website',
                  issue_number : prNumber,
                  body : 'You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message in error, please message us in the #hfla-site team slack channel with the link to this PR.'
                });
              }
              }
            

          
            

  
