name: Add Pull Request Instructions
on:
  pull_request:
    types: [opened]
    branches:
      - 'gh-pages'
      - 'feature-homepage-launch'
      - 'abc'

jobs:
  Add-Pull-Request-Instructions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create the message to post
      - name: Create Instruction
        uses: actions/github-script@v7
        id: instruction
        with:
          script: |
            const script = require('./github-actions/pr-instructions/create-instruction.js')
            console.log(context)
      

