name: Pull Request Verification
on:
  pull_request_target:
    types: [opened]
    branches:
      - 'gh-pages'
      - 'verify-pr-creator-util-3906'

jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HFLA_PA_TOKEN }}
          script: |
            const verifyPR = require('./github-actions/trigger-pr-target/verify-pr.js');
            verifyPR({github, context});